### ISSUE TITLE
Assign masks for training

### ISSUE THREAD

**Issue by wmrenr** [NilsBochow/lama_reconstruction#1]
Hello, I want to use the designated mask for training. Can you share your idea and code changes based on lama?

**Comment by NilsBochow** [comment]
Hi, 
the main changes are in [saicinpainting/training/data/masks.py](https://github.com/spin0r/lama_reconstruction/commit/9b37e86e9dede90c8e779fdda5ab29a689ab22d0#diff-7108b9e98886fa802c7a94b62eddbc2c6c69ff67e8fc8fc99b4f5bf6ba792362) and [bin/gen_mask_dataset.py](https://github.com/spin0r/lama_reconstruction/commit/9b37e86e9dede90c8e779fdda5ab29a689ab22d0#diff-abdfdba3cf5090dd17e6879749126d25e738d35781985fe84b31d53cf7261dbb). I created two different MaskGenerators one that draws a random mask from a .h5 file and one that chooses a mask in the order of the file. 

In the training process you have to change the key in the file [saicinpainting/training/data/datasets.py](https://github.com/spin0r/lama_reconstruction/commit/13d54667bf7f3240d932395f4b364a901a611220#diff-d3b3e07c2d1145588ec32b5dba6fe3d5ec96c1aee94b25ad65fe2f7aaa1edc7c) from "mixed" to "fixed" (randomly drawn mask from .h5 file). The masks for validation, test and visual_test are created beforehand via [bin/gen_mask_dataset.py](https://github.com/spin0r/lama_reconstruction/commit/9b37e86e9dede90c8e779fdda5ab29a689ab22d0#diff-abdfdba3cf5090dd17e6879749126d25e738d35781985fe84b31d53cf7261dbb). However there you need to change the key in the config files. 

Is this clear enough?
